fragment CloudProviderYodaConfigFragment on CloudProviderYodaConfig {
    id
    awsConfig {
        ...AWSYodaConfigFragment
    }
    azureConfig {
        ...AzureYodaConfigFragment
    }
    gcpConfig {
        id
    }
}