fragment DataStorageFragment on DataStorage {
    id
    name
    cloudProfile {
        ...CloudProfileFragment
    }
    cloudProviderYodaConfig {
        ...CloudProviderYodaConfigFragment
    }
}


query GetDataStorage($where: DataStorageWhereUniqueInput!) {
    dataStorage(where: $where) {
        ...DataStorageFragment
    }
}

query GetDataStorageContainer($where: DataStorageContainerWhereUniqueInput!) {
    dataStorageContainer(where: $where) {
        id
        directoryName
        cloudName
        dataStorageId
    }
}