fragment ProjectFragment on Project {
    id
    name
    createdAt
}


query GetProjects($whereAccount: AccountWhereUniqueInput!, $whereProject: ProjectWhereInput) {
  projects(whereAccount: $whereAccount, whereProject: $whereProject) {
    ...ProjectFragment
  }
}


mutation CreateProject($whereAccount: AccountWhereUniqueInput!, $data: CreateProjectInput!){
    createProject(
        data: $data,
        whereAccount: $whereAccount
    ){
        ...ProjectFragment
    }
}